version: "3"

services:
  app:
    build:
      context: . 
    volumes:
      - ./projects:/usr/src/
    ports:
     - "8888:8888"
    command: >
      sh -c "jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root"
